package com.escapeRoom.entity;

public  enum  ItemType {

    WINDOW, KEY, CODE, DOOR, CONTAINER, PROTECTCONTAINER, COIN, MERCHANT,FIRSTAIDKIT,PORTAL,PICTURE,
    FURNITURE, MESSAGE,LAMP, MIRROR, BUTTON,




}
