package com.escapeRoom.entity;

public  enum  ItemType {

    WINDOW, KEY, CODE, DOOR, CONTAINER, PROTECTCONTAINER, COIN, MERCHANT,FIRSTAIDKIT,PORTAL,PICTURE,
    FURNITURE, MESSAGE,LAMP, MIRROR, BUTTON, BOOK, FIGURINE, WEIGHTMECHANISM, WEIGHTFORSCALE, MIRRORFORRIDDLE
    ,FLASHLIGHT, ELECTRICBOX, FUSE, BLACKWALL, GALLERY;

}
